version: '3'

services:

  clicks-postgres:
    image: postgres
    container_name: clicks-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $SQL_PASSWORD
      POSTGRES_USER: $SQL_USERNAME
      POSTGRES_DB: $SQL_DBNAME
    ports:
      - '5432:5432'
    volumes: 
      - ./host-folder/:/var/lib/postgresql/data/
     